### ISSUE TITLE
无法识别环境路径，出现乱码情况

### ISSUE THREAD

**Issue by jiang-taibai** [jiang-taibai/development-booster#1]
# 1. 描述

当选择 `conda.exe` 时，路径为 `D:\Program Files (x86)\conda\Scripts\conda.exe`，提示路径无效，并乱码输出。

![d2a313054601932f83515973c449949b](https://github.com/jiang-taibai/development-booster/assets/66373624/f7bc8d26-bad3-466c-9bc5-3c169cbfc768)

# 2. 可能的原因

在开发环境中未测试到带有空格、特殊符号（例如括号）等情况，推测应当是由于命令中如果有空格会导致命令执行错误。

**Comment by Woohoy** [comment]
持续跟进

**Comment by jiang-taibai** [comment]
针对该问题，发布 [开发加速器 v1.1.1](https://github.com/jiang-taibai/development-booster/releases/tag/v1.1.1) ，并测试通过。

**Comment by jiang-taibai** [comment]
针对该问题，发布 [开发加速器 v1.1.1](https://github.com/jiang-taibai/development-booster/releases/tag/v1.1.1) ，并测试通过。

![77b94b1c6472b2554db4edf9e323af2e](https://github.com/jiang-taibai/development-booster/assets/66373624/48ac6216-fa81-4147-b784-672c2665e1aa)
